<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-09-12T17:43:56+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Europe/Berlin',
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyCwh8oK-5VjBnpo0whchYVx3gec4hqm64E',
        ],
    ],
];
