<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-09-13T18:44:41+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'locale' => 'de_DE',
    'version_installed' => '8.2.1',
    'version_db_installed' => '20170802000000',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1504849240,
        'latest_version' => '8.2.1',
        'do_page_reindex_check' => false,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => false,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => true,
        'generate_less_sourcemap' => false,
    ],
    'file_manager' => [
        'restrict_uploaded_image_sizes' => false,
        'restrict_max_width' => 1920,
        'restrict_max_height' => 1080,
        'restrict_resize_quality' => 60,
    ],
];
