<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-09-12T18:17:41+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.misc.modern_tile_thumbnail_bgcolor
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Schmink Schmid',
            'misc' => [
                'favicon_fid' => 15,
                'iphone_home_screen_thumbnail_fid' => 15,
                'modern_tile_thumbnail_fid' => 15,
                'modern_tile_thumbnail_bgcolor' => '',
            ],
        ],
    ],
];
